#!/usr/bin/env sh
#YABAI STUFF

# == Config ==
yabai -m config layout bsp
yabai -m config top_padding 2
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10   
yabai -m config external_bar all:32:0
yabai -m config focus_follows_mouse off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config active_window_opacity 1.0

# == Border Settings ==
yabai -m config window_border on
yabai -m config active_window_border_color 0xFF40FF00
yabai -m config window_border_width 2
yabai -m config normal_window_border_color 0xff3883ca


# == Additionall Settings ==
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
yabai -m config mouse_modifier ctrl #set mouse interaction modifier key (default: fn)
yabai -m config mouse_action2 resize    # set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action1 move  # set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_drop_action swap

# === Custom Space Labels ====
yabai -m space 1 --label home
yabai -m space 2 --label study
yabai -m space 3 --label news
yabai -m space 4 --label love
yabai -m space 5 --label extra
#yabai -m space 5 --label five


# === Rules ===
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^CleanShot$" manage=off layer=above
yabai -m rule --add app="^Spotify$" manage=off layer=above
yabai -m rule --add app="^Skim$" space=2 border=off manage=on
yabai -m rule --add app="^Skype$" display=2 border=off
yabai -m rule --add app="^Mail$" space=3
yabai -m rule --add app="^Reeder$" space=3
yabai -m rule --add app="^Microsoft Teams$" space=2
yabai -m rule --add app="^Microsoft Outlook$" space=2
yabai -m rule --add app="^Microsoft OneNote$" space=2

# === Space Specific config ===
yabai -m config --space 2 layout float  #set space 2 to float

# === Signal ===
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_created action="sketchybar -m --trigger window_created &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_destroyed &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
yabai -m signal --add event=window_resized action="sketchybar -m --trigger window_resized &> /dev/null"
yabai -m signal --add event=window_created app="^Skim$" action="yabai -m window \$YABAI_WINDOW_ID --toggle float;sketchybar -m --trigger float_change"
yabai -m signal --add event=display_changed action="brew services restart"



echo "yabai configuration loaded.."

#END      